# verify all solb_<n>.txt (two-sided construction) and sol_<n>.txt against the group generated by the exported generators
Read("/project/work/p20_37/verify.g");
files := Filtered(DirectoryContents("/project/work/p20_37"), f -> StartsWith(f, "solb_") or StartsWith(f, "sol_"));
Sort(files, function(a,b) return Int(Filtered(a, IsDigitChar)) < Int(Filtered(b, IsDigitChar)); end);
total := 0; bad := 0;
for f in files do
  n := Int(Filtered(f, IsDigitChar));
  cf := Concatenation("/project/work/p20_37/case", ReplacedString(f{[4..Length(f)]}, "sol", ""));   # sol_ -> case_, solb_ -> caseb_
  if StartsWith(f, "solb_") then cf := Concatenation("/project/work/p20_37/caseb_", String(n), ".txt"); else cf := Concatenation("/project/work/p20_37/case_", String(n), ".txt"); fi;
  if not IsExistingFile(cf) then continue; fi;
  lines := Filtered(SplitString(StringFile(cf), "\n"), l -> l <> "");
  ng := Int(lines[3]);
  gens := List([4..3+ng], i -> PermList(List(SplitString(lines[i], " "), Int) + 1));
  G := Group(gens);
  if Size(G) <> n then Print(f, ": ORDER MISMATCH\n"); continue; fi;
  sl := Filtered(SplitString(StringFile(Concatenation("/project/work/p20_37/", f)), "\n"), l -> l <> "");
  if Length(sl) = 0 then continue; fi;
  Print(f, " |G| = ", n, " (", StructureDescription(G), "): ", Length(sl)/3, " factorisations\n");
  if not VerifySol(G, Concatenation("/project/work/p20_37/", f)) then bad := bad + 1; fi;
  total := total + Length(sl)/3;
od;
Print("TOTAL verified factorisations: ", total, " files with failures: ", bad, "\nFINISHED\n"); QUIT;
