# pc-group version of the 13.19 construction
F := FreeGroup("e1","f1","e2","f2","e3","f3","u12","u13","u23");
g := GeneratorsOfGroup(F); e := [g[1],g[3],g[5]]; f := [g[2],g[4],g[6]]; u12 := g[7]; u13 := g[8]; u23 := g[9];
w := [[u12,u12,u13],[u12,u23,u23],[u13,u23,u13]];
rels := List(g, x -> x^2);
for x in [u12,u13,u23] do for y in g do Add(rels, Comm(x,y)); od; od;
for i in [1..3] do for j in [1..3] do
  if i = j then Add(rels, Comm(e[i],f[i]) * w[i][i]^-1);
  else Add(rels, Comm(e[i],f[j]) * w[i][j]^-1); Add(rels, Comm(e[i],e[j])); Add(rels, Comm(f[i],f[j])); fi;
od; od;
Gfp := F / rels;
iso := IsomorphismPcGroup(Gfp); Q := Image(iso);
Print("|Q| = ", Size(Q), " class ", NilpotencyClassOfGroup(Q), "\n");
im := x -> Image(iso, Image(GroupHomomorphismByImages(F, Gfp, g, GeneratorsOfGroup(Gfp)), x));
E := List(e, im); Fg := List(f, im); U12 := im(u12); U13 := im(u13); U23 := im(u23);
A := Subgroup(Q, [U12,U13,U23]); A0 := Subgroup(Q, [U12*U13, U13*U23]);
N := [Subgroup(Q, [E[1],Fg[1],U12,U13]), Subgroup(Q, [E[2],Fg[2],U12,U23]), Subgroup(Q, [E[3],Fg[3],U13,U23])];
Print("|N_i| = ", List(N, Size), " normal: ", List(N, S -> IsNormal(Q,S)), " |N1 meet N2 meet N3| = ", Size(Intersection(N)), " |N1 meet N2|=", Size(Intersection(N[1],N[2])), "\n");
Hhat := ClosureGroup(A, [E[1]*E[2], E[2]*E[3], Fg[1]*Fg[2], Fg[2]*Fg[3]]);
Print("|Hhat| = ", Size(Hhat), " Hhat/A0 elementary abelian: ", IsElementaryAbelian(Hhat/A0), "\n");
found := false;
for H in Filtered(List(ConjugacyClassesSubgroups(Hhat), Representative), S -> Index(Hhat, S) = 2) do
  for Hc in AsList(ConjugacyClassSubgroups(Hhat, H)) do
    if not IsNormal(Q, Hc) or Intersection(Hc, A) <> A0 then continue; fi;
    if not ForAll(N, Ni -> Size(ClosureGroup(Hc, Ni)) = Size(Q)) then continue; fi;
    P := Q / Hc;
    Print("FOUND H (order ", Size(Hc), "): Q/H = ", StructureDescription(P), ", abelian: ", IsAbelian(P), "; H generated by ", List(GeneratorsOfGroup(Hc), x -> Factorization(Q, x)), "\n");
    Gi := List(N, Ni -> Q/Ni);
    Print("G_i = Q/N_i: ", List(Gi, StructureDescription), " sizes ", List(Gi, Size), "\n");
    Print("H maps onto each G_i: ", List(N, Ni -> Size(ClosureGroup(Hc, Ni)) = Size(Q)), "\n");
    found := true; break;
  od;
  if found then break; fi;
od;
Print("FINISHED\n"); QUIT;
