# Uniform construction for 13.19: P a p-group of class c, n = c+1 blocks. Q <= prod over nonempty S subset [n] of copies P^(S),
# generated by tagged generators g^[i] = (g if i in S else 1)_S. H = kernel of projection to the full copy; N_i = elements trivial
# in all copies S not containing i. Then Q/H ~= P, H N_i = Q, and the intersection of the N_i is Q meet P^([n]).
Tagged := function(P, n, name)
  local gens, subsets, D, embs, tg, i, S, g, Q, full, H, N, I, fullidx, projfull, Pq, ok;
  gens := GeneratorsOfGroup(P);
  subsets := Filtered(Combinations([1..n]), S -> Length(S) > 0);
  D := DirectProduct(List(subsets, S -> P));
  embs := List([1..Length(subsets)], t -> Embedding(D, t));
  tg := [];
  for i in [1..n] do for g in gens do
    Add(tg, Product(Filtered([1..Length(subsets)], t -> i in subsets[t]), t -> Image(embs[t], g)));
  od; od;
  Q := Subgroup(D, tg);
  fullidx := Position(subsets, [1..n]);
  projfull := Projection(D, fullidx);
  H := Kernel(RestrictedMapping(projfull, Q));   # elements of Q trivial in the full copy
  Pq := Image(RestrictedMapping(projfull, Q));
  # simpler: N_i = elements of Q whose projections to copies S not containing i are trivial
  N := List([1..n], i -> Intersection(List(Filtered([1..Length(subsets)], t -> not i in subsets[t]), t -> Kernel(RestrictedMapping(Projection(D, t), Q)))));
  I := Intersection(N);
  Print(name, ": |P|=", Size(P), " class ", NilpotencyClassOfGroup(P), " n=", n, " |Q|=", Size(Q), " |H|=", Size(H), " Q/H ~= P: ", Size(Pq) = Size(P) and IdGroup(Pq) = IdGroup(P), "\n");
  Print("   |N_i| = ", List(N, Size), " normal: ", List(N, S -> IsNormal(Q,S)), " H N_i = Q: ", List(N, Ni -> Size(ClosureGroup(H, Ni)) = Size(Q)), " |meet N_i| = ", Size(I), "\n");
  return [Q, H, N];
end;
r := Tagged(DihedralGroup(IsPermGroup, 8), 3, "D8 (p=2, n=3)");
r := Tagged(WreathProduct(CyclicGroup(IsPermGroup,3), CyclicGroup(IsPermGroup,3)), 4, "C3 wr C3 (p=3, n=4)");
Print("regular? Q/H for C3 wr C3: exponent ", Exponent(WreathProduct(CyclicGroup(IsPermGroup,3), CyclicGroup(IsPermGroup,3))), "\n");
QUIT;
