# 18.119 (Shumyatsky): w multilinear commutator word; is every Sylow p-subgroup of w(G) generated by w-values?
CommSet := function(A, B) local s, a, b; s := []; for a in A do for b in B do AddSet(s, Comm(a,b)); od; od; return s; end;
CheckGroup := function(G, id)
  local E, C, G3, D2, D3, words, name, W, V, p, P, gens, i;
  E := Elements(G);
  C := CommSet(E, E);                     # [x,y]
  G3 := CommSet(C, E);                    # [x,y,z]
  D2 := CommSet(C, C);                    # [[x,y],[z,t]]
  D3 := CommSet(D2, D2);                  # delta_3
  words := [["[x,y]", C], ["[x,y,z]", G3], ["[[x,y],[z,t]]", D2], ["delta3", D3], ["[[x,y],[z,t],u]", CommSet(D2, E)], ["[[x,y,z],[t,u]]", CommSet(G3, C)]];
  for i in [1..Length(words)] do
    W := words[i][2]; V := Subgroup(G, W);
    if Size(V) = 1 then continue; fi;
    for p in PrimeDivisors(Size(V)) do
      P := SylowSubgroup(V, p);
      if Size(Subgroup(V, Filtered(W, w -> w in P))) <> Size(P) then
        Print("COUNTEREXAMPLE ", id, " ", StructureDescription(G), " word ", words[i][1], " p=", p, " |P|=", Size(P), " generated by w-values in P: ", Size(Subgroup(V, Filtered(W, w -> w in P))), "\n");
      fi;
    od;
  od;
end;
for n in [2..400] do
  for k in [1..NrSmallGroups(n)] do
    G := SmallGroup(n,k);
    if IsAbelian(G) then continue; fi;
    CheckGroup(G, [n,k]);
  od;
  if n mod 20 = 0 then Print("done order ", n, "\n"); fi;
od;
Print("FINISHED\n"); QUIT;
