# C.13 (14.72): independent check of the surface X, its fixed locus, invariants and the class-group obstruction
from sympy import symbols, groebner, expand, simplify, I, together
x,y,u,v,A,V,D,t = symbols('x y u v A V D t')
f1 = y**2 - x**3 + x; f2 = y*u - x*v; f3 = (x**2-1)*u - y*v
# sigma has order 4 and preserves the ideal
sig = lambda e: e.subs({x:-x, y:I*y, u:I*u, v:v}, simultaneous=True)
print("sigma^4 = id on generators:", [simplify(sig(sig(sig(sig(g))))-g) for g in (x,y,u,v)])
for name,f in [('f1',f1),('f2',f2),('f3',f3)]:
    print(name, "-> ", simplify(sig(f)), " (multiple of a generator)")
# smoothness: saturation of ideal + 2x2 minors of Jacobian
from sympy import Matrix
J = Matrix([[f.diff(z) for z in (x,y,u,v)] for f in (f1,f2,f3)])
minors = [J[list(r),list(c)].det() for r in [(0,1),(0,2),(1,2)] for c in [(0,1),(0,2),(0,3),(1,2),(1,3),(2,3)]]
G = groebner([f1,f2,f3]+minors, x,y,u,v, order='lex')
print("Groebner basis of (equations + 2x2 minors):", list(G.exprs)[:3], "...", "=> singular locus empty:", list(G.exprs)==[1])
# fixed locus ideal
print("fixed ideal generated by (2x,(1-i)y,(1-i)u) i.e. (x,y,u); check it is sigma-stable and in X:",
      simplify(sig(x)+x), simplify(sig(y)-I*y))
# invariants and relations
d = x*u**2 - v**2; a = x**2
print("a,v,d invariant:", simplify(sig(a)-a), simplify(sig(v)-v), simplify(sig(d)-d))
r1 = expand(x*d - u**2); r2 = expand((x**2-1)*d - v**2)
G2 = groebner([f1,f2,f3], x,y,u,v, order='lex')
print("x*d - u^2 in ideal:", G2.reduce(r1)[1] == 0, "   (x^2-1)*d - v^2 in ideal:", G2.reduce(r2)[1] == 0)
# elimination: invariant ring presentation
GE = groebner([f1,f2,f3, A-x**2, V-v, D-(x*u**2-v**2)], x,y,u,v,A,V,D, order='lex')
elim = [g for g in GE.exprs if not (g.has(x) or g.has(y) or g.has(u) or g.has(v))]
print("eliminated ideal:", elim)
