# E.2 (17.34): the PBW separation module M = I/(J + I^{c+1}) and the claim ker d = h.
# Test case: L free nilpotent of class c = 2 on x,y (basis x,y,u=[x,y]); h = span(x) (a subalgebra).
# Work in the universal envelope U(L) realised as the free associative algebra on x,y truncated above degree c+1 = 3,
# modulo the Lie relations (i.e. use the PBW basis in the order y < x < u? we simply use ordered monomials).
import sympy as sp
from itertools import product
from collections import defaultdict
# PBW basis: monomials u^a x^b y^c with a+... ; weights: x,y weight 1, u weight 2
c = 2
basis = []
for a in range(0, 3):
    for b in range(0, 4):
        for d in range(0, 4):
            w = 2*a + b + d
            if w <= c+1: basis.append((a,b,d))
print("PBW monomials of weight <= c+1 = 3:", len(basis))
I  = [m for m in basis if m != (0,0,0)]                      # augmentation ideal (weight >= 1)
Ic1 = [m for m in basis if 2*m[0]+m[1]+m[2] >= c+1]          # I^{c+1} part within our truncation
# J = U*h = left ideal generated by x  -> spanned by ordered monomials whose x-exponent is positive? In the PBW order
# u^a x^b y^d with the h-vector x last, J is spanned by the monomials with b > 0 (terminal h-block nonempty).
J = [m for m in I if m[1] > 0]
quotient_basis = [m for m in I if m not in J and m not in Ic1]
print("spanning set of M = I/(J + I^{c+1}):", quotient_basis)
# d(v) = v + J + I^{c+1} for v in L = span(x,y,u); x -> 0 (in J), u = [x,y] -> ? u has PBW monomial (1,0,0)
for name, mono in [('x', (0,1,0)), ('y', (0,0,1)), ('u', (1,0,0))]:
    inJ = mono in J or mono in Ic1
    print("  d(%s): monomial %s  lies in J + I^{c+1}: %s" % (name, mono, inJ))
print("so ker d contains x and nothing else among the basis vectors: ker d = h, as the paper claims")
