# Check of Theorem 4.3 (Problem 20.108): G = (C11 x C11) x| C5, generator acts by diag(3,9)
els := [];; for x in [0..10] do for y in [0..10] do for k in [0..4] do Add(els,[x,y,k]); od; od; od;
idx := function(t) return (t[1] mod 11)*55 + (t[2] mod 11)*5 + (t[3] mod 5) + 1; end;;
mul := function(a,b) return [ (a[1] + 3^a[3]*b[1]) mod 11, (a[2] + 9^a[3]*b[2]) mod 11, (a[3]+b[3]) mod 5 ]; end;;
Print("index check: ", ForAll([1..605], i -> idx(els[i]) = i), "\n");
toperm := f -> PermList(List(els, t -> idx(f(t))));;
gG := [[1,0,0],[0,1,0],[0,0,1]];;
lam := List(gG, g -> toperm(t -> mul(g,t)));;        # left translations
L := Group(lam);; Print("|lambda(G)| = ", Size(L), "\n");
# abstract group, centre, automorphism group order
f := FreeGroup("a","b","c");; a:=f.1;; b:=f.2;; c:=f.3;;
Gab := f/[a^11,b^11,c^5,Comm(a,b), c*a*c^-1*a^-3, c*b*c^-1*b^-9];;
Gp := Image(IsomorphismPermGroup(Gab));;
Print("|G| = ", Size(Gp), "  |Z(G)| = ", Size(Centre(Gp)), "  |Aut(G)| = ", Size(AutomorphismGroup(Gp)), "\n");
# holomorph as generated by left translations and the claimed automorphisms (fix identity)
autmap := function(A,B,D,E) return t -> [ (A*t[1] + B*(1-3^t[3])) mod 11, (D*t[2] + E*(1-9^t[3])) mod 11, t[3] ]; end;;
# verify these are automorphisms for all parameters (spot: generators of parameter group) 
isHom := function(phi) return ForAll(els, s -> ForAll(gG, g -> phi(mul(s,g)) = mul(phi(s),phi(g)))); end;;
Print("claimed automorphisms are homomorphisms: ", ForAll([[2,0,1,0],[1,1,1,0],[1,0,2,0],[1,0,1,1]], p -> isHom(autmap(p[1],p[2],p[3],p[4]))), "\n");
autperms := List([[2,0,1,0],[1,1,1,0],[1,0,2,0],[1,0,1,1]], p -> toperm(autmap(p[1],p[2],p[3],p[4])));;
Hol := Group(Concatenation(lam, autperms));;
Print("|Hol| = ", Size(Hol), "  expected 605*12100 = ", 605*12100, "\n");
Print("Normalizer(Sym(605), lambda(G)) = Hol ? ");
NL := Normalizer(SymmetricGroup(605), L);; Print(Size(NL) = Size(Hol) and IsSubgroup(NL,Hol), "\n");
theta := toperm(t -> [ t[2], (3^((-t[3]) mod 5) * t[1]) mod 11, (2*t[3]) mod 5 ]);;
Print("theta normalises Hol: ", ForAll(GeneratorsOfGroup(Hol), h -> h^theta in Hol), "\n");
Print("theta^2 in Hol: ", theta^2 in Hol, "   theta^4 = 1: ", IsOne(theta^4), "  theta in Hol: ", theta in Hol, "\n");
QUIT;
